### ISSUE TITLE
Unable to install from Git

### ISSUE THREAD

**Issue by clin1234** [jippi/dottie#39]
Running `go install github.com/jippi/dottie/cmd@main` yielded this:
```
go: downloading github.com/jippi/dottie v0.11.3-0.20240507115018-9221955c336b
go: github.com/jippi/dottie/cmd@main (in github.com/jippi/dottie@v0.11.3-0.20240507115018-9221955c336b):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by jippi** [comment]
Ah; I guess that's broken currently due to some bug fixes in my forks that's pending upstream :) 

For now you have to use one of the other installation options

**Comment by jippi** [comment]
Also; I need to update the docs `go install github.com/jippi/dottie@main` is the correct command after a refactor (maybe that works?)

**Comment by clin1234** [comment]
Still got the same error with `go install github.com/jippi/dottie@main`
